### ISSUE TITLE
A bug fixed for tracking.py

### ISSUE THREAD

**Issue by gmh14** [AlexQie/MDNet#2]
Hi, very thanks for the wonderful tensorflow implementation! I find a little bug in tracking.py. For line 123 in function init_networks(), the arg should be "logits= online_fc6", because the function "tf.nn.sparse_softmax_cross_entropy_with_logits" has already included the softmax operation. After fixing this, the code works really well. Thank you again!

**Comment by AlexQie** [comment]
Thank you. I wrote this code last year and I tested the performance on the OTB dataset, but there is a large performance gap between this version and the author's version (about 10% on success rate). Unfortunately, I have not figured out where the problem is. I will fix the bug you reported but I am still not sure whether there are other bugs. So I do NOT recommend you to use this code in your project. 
Appreciate your attention, thank you.

**Comment by zhucheng725** [comment]
Hello, I meet some problems that the data file has a little bug which the model.ckpt-5799.data can not use and must change it to another name 'model.ckpt-5799.data-00000-of-00001'.
Another problem is that when I do this command: $python3 tracking.py and the terminal shows as follow:

Traceback (most recent call last):
  File "tracking.py", line 368, in <module>
    tracking(im_list, gt[0, :])
  File "tracking.py", line 160, in tracking
    images_tensor, conv3_feature, classify_input, label_input, logits_op, train_step, cross_entropy_mean = init_networks(sess)
  File "tracking.py", line 82, in init_networks
    fc4_weight, fc4_biase, fc5_weight, fc5_biase = load_model(sess)
  File "tracking.py", line 75, in load_model
    fc4_weight, fc4_biase, fc5_weight, fc5_biase = sess.run([fc4_weight, fc4_biase, fc5_weight, fc5_biase])
  File "/home/zhu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/zhu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1105, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/zhu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 414, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/zhu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/zhu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/zhu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 341, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/zhu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 231, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>

How to solve it

**Comment by zhucheng725** [comment]
I found that mistake that your .ckpt do not have fc4/biases:0 and your .ckpt' names as follow:

tensor_name:  fc6/weights
tensor_name:  fc6/biases
tensor_name:  fc5/weight_loss/avg
tensor_name:  fc4/weights
tensor_name:  fc5/biases
tensor_name:  fc4/weight_loss/avg
tensor_name:  total_loss/avg
tensor_name:  cross_entropy/avg
tensor_name:  conv1/weight_loss/avg
tensor_name:  fc6/weight_loss/avg
tensor_name:  conv1/weights
tensor_name:  conv3/biases
tensor_name:  conv2/biases
tensor_name:  fc5/weights
tensor_name:  conv3/weights
tensor_name:  conv1/biases
tensor_name:  conv2/weight_loss/avg
tensor_name:  conv2/weights
tensor_name:  conv3/weight_loss/avg

how to solve it?

**Comment by zhucheng725** [comment]
I try to change the 'fc4_biases' to 'fc6_biases', 'fc6_weights' to 'fc6_weights'.
And I run this code tracking.py and show new errors:
KeyError: "The name 'images:0' refers to a Tensor which does not exist. The operation, 'images', does not exist in the graph."
So can you solve this problem?
Thanks.

**Comment by zhucheng725** [comment]
> Hi, very thanks for the wonderful tensorflow implementation! I find a little bug in tracking.py. For line 123 in function init_networks(), the arg should be "logits= online_fc6", because the function "tf.nn.sparse_softmax_cross_entropy_with_logits" has already included the softmax operation. After fixing this, the code works really well. Thank you again!

Why would I meet lots of problem? Do you change any other things to run this code?
